require.config({
    paths: {
        "rd.styles.animate": "../rdk/css/theme/zte-blue/rdk-animate-style",
        "rd.styles.Accordion": "../rdk/css/theme/zte-blue/rdk-accordion-style",
        "rd.styles.Alert": "../rdk/css/theme/zte-blue/rdk-Alert-style",
        "rd.styles.Area": "../rdk/css/theme/zte-blue/rdk-area-style",
        "rd.styles.BasicSelector": "../rdk/css/theme/zte-blue/rdk-basicselector-style",
        "rd.styles.ListSelector": "../rdk/css/theme/zte-blue/rdk-listselector-style",
        "rd.styles.Bullet": "../rdk/css/theme/zte-blue/rdk-bullet-style",
        "rd.styles.Button": "../rdk/css/theme/zte-blue/rdk-button-style",
        "rd.styles.ButtonGroup": "../rdk/css/theme/zte-blue/rdk-buttongroup-separator-style",
        "rd.styles.ComboSelect": "../rdk/css/theme/zte-blue/rdk-comboselect-style",
        "rd.styles.Graph": "../rdk/css/theme/zte-blue/rdk-graph-style",
        "rd.styles.Input":"../rdk/css/theme/zte-blue/rdk-input-style",
        "rd.styles.Panel": "../rdk/css/theme/zte-blue/rdk-panel-style",
        "rd.styles.PopupService": "../rdk/css/theme/zte-blue/rdk-PopupService-style",
        "rd.styles.ProgressBar": "../rdk/css/theme/zte-blue/rdk-progressbar-style",
        "rd.styles.ScoreIndicator": "../rdk/css/theme/zte-blue/rdk-scoreindicator-style",
        "rd.styles.Scroll": "../rdk/css/theme/zte-blue/perfect-scrollbar-style",
        "rd.styles.Scroller": "../rdk/css/theme/zte-blue/rdk-scroller-style",
        "rd.styles.SingleIndicator": "../rdk/css/theme/zte-blue/rdk-singleindicator-style",
        "rd.styles.Steps": "../rdk/css/theme/zte-blue/rdk-steps-style",
        "rd.styles.Tab": "../rdk/css/theme/zte-blue/rdk-tab-style",
        "rd.styles.Table": "../rdk/css/theme/zte-blue/rdk-table-style",
        "rd.styles.TabSelect": "../rdk/css/theme/zte-blue/rdk-tabselect-style",
        "rd.styles.TabSelector": "../rdk/css/theme/zte-blue/rdk-tabselector-style",
        "rd.styles.Theme": "../rdk/css/theme/zte-blue/rdk-theme-style",
        "rd.styles.Time": "../rdk/css/theme/zte-blue/rdk-time-style",
        "rd.styles.TimeBasic": "../rdk/css/theme/zte-blue/rdk-time-basic-style",
        "rd.styles.TimeSelect": "../rdk/css/theme/zte-blue/rdk-time-select-style",
        "rd.styles.Tree": "../rdk/css/theme/zte-blue/rdk-tree-style",
        "rd.styles.Switch": "../rdk/css/theme/zte-blue/rdk-switch-style",
        "rd.styles.NumericInput": "../rdk/css/theme/zte-blue/rdk-numericinput-style",
        "rd.styles.NotifyService": "../rdk/css/theme/zte-blue/rd-NotifyService-style",
        "rd.styles.MenuService": "../rdk/css/theme/zte-blue/rd-MenuService-style",
        "rd.styles.tableResize": "../rdk/css/theme/zte-blue/rdk-table-resize-style",
    }
});
