require.config({
    //下载依赖超时时间，0为不超时
    waitSeconds: 30,
    paths: {
        "rd.styles.Input": "../rdk/controls/assets/rdk-input-style",
        "rd.styles.PopupService": "../rdk/services/assets/rdk-PopupService-style",
        "rd.styles.Accordion": "../rdk/containers/assets/rdk-accordion-style",
        "rd.styles.Alert": "../rdk/services/assets/rdk-Alert-style",
        "rd.styles.Area": "../rdk/controls/assets/rdk-area-style",
        "rd.styles.BasicSelector": "../rdk/controls/assets/rdk-basicselector-style",
        "rd.styles.Bullet": "../rdk/controls/assets/rdk-bullet-style",
        "rd.styles.Button": "../rdk/controls/assets/rdk-button-style",
        "rd.styles.ButtonGroup": "../rdk/containers/assets/rdk-buttongroup-separator-style",
        "rd.styles.ComboSelect": "../rdk/controls/assets/rdk-comboselect-style",
        "rd.styles.Graph": "../rdk/controls/assets/rdk-graph-style",
        "rd.styles.Panel": "../rdk/containers/assets/rdk-panel-style",
        "rd.styles.ProgressBar": "../rdk/controls/assets/rdk-progressbar-style",
        "rd.styles.ScoreIndicator": "../rdk/controls/assets/rdk-scoreindicator-style",
        "rd.styles.Scroller": "../rdk/controls/assets/rdk-scroller-style",
        "rd.styles.Scroll": "../rdk/attributes/assets/perfect-scrollbar-style",
        "rd.styles.SingleIndicator": "../rdk/controls/assets/rdk-singleindicator-style",
        "rd.styles.Tab": "../rdk/containers/assets/rdk-tab-style",
        "rd.styles.Table": "../rdk/controls/assets/rdk-table-style",
        "rd.styles.TabSelect": "../rdk/controls/assets/rdk-tabselect-style",
        "rd.styles.TabSelector": "../rdk/controls/assets/rdk-tabselector-style",
        "rd.styles.Theme": "../rdk/attributes/assets/rdk-theme-style",
        "rd.styles.Time": "../rdk/controls/assets/rdk-time-style",
        "rd.styles.Tree": "../rdk/controls/assets/rdk-tree-style",
    }
});
